Nombre de los participantes Prueba1
Juan José Naranjo Velásquez CC : 1039474689
Alejandro Mora Suarez CC: 1128437044
Kenneth David Leonel Triana CC: 1192817456


Ejercio Parte 1

In [5]:
#Creación de la clase Pedido 
#Generación de la clase que funcione correctamente con al menos 2 métodos y 2 atributos. 
class Pedido:
    """
    Documentación Clase Pedido 
    Esta clase servira para la toma de uestros productos de mercado, en donde el usuario podrá hacer el pedido, retirarlo y calcular el costo de este
    
    args: 
    id_pedido: int
    fecha:str
    costo_pedido:float
    descuento_pedido:float
    """
    def __init__(self, id_pedido: int, fecha: str, productos:list, cantidades:list, precios:list):
        """
        Se iniciailiza un Pedido con sus atributos
            id_pedido: int -> Identificador del pedido
            fecha: str -> Fecha en la que se realizó el pedido
            costo_pedido: float -> Costo total del pedido
            productos: list -> Lista de productos del pedido
            cantidades: list -> Lista de cantidades de cada producto
            precios: list -> Lista de precios de cada producto
        """
        self.id_pedido = id_pedido
        self.fecha = fecha
        self.productos = []
        self.cantidades = []
        self.precios = []

    def calcularCostoPedido(self,cantidades,precios):
        """
        función que calcula el costo del pedido realizado.
        argumentos: 
        In[0]:
        Out[0]:
        """
        total = sum(cantidad * precio for cantidad, precio in zip(cantidades, precios))
        return total
    def hacerPedido(self, productos:list, cantidades:list, precios:list):
        """"
        Se realiza un pedido, para ello la función va recibir los siguientes parametros
        productos: str -> Lista de productos del pedido
        cantidades: int -> Lista de cantidades de cada producto
        precios: int -> Lista de precios de cada producto
        """
        if len(productos) == len(cantidades) == len(precios):
            self.productos.append(productos)
            self.precios.append(precios)
            self.cantidades.append(cantidades)
            valorPedido = self.calcularCostoPedido(cantidades,precios)
            return f"El pedido se realizo con exito con el valor total de :{valorPedido} pesos colombianos"
            
        else:
            raise ValueError("Las listas deben ser del mismo tamaño")
        



In [6]:
#se crea la clase hija  donde su padre es Pedido
class Usuario (Pedido): 
     """"
     Documentación Clase Usuario

     Esta clase hereda los atributos de la Clase Pedido para establecer los detalles de la persona que realiza el pedido

     args:

    nombre:str
    apellido:str
    cedula:int
    direccion:str
    telefono:int
    email:str

     """
     def __init__(self,id_pedido: int, fecha: str, productos:list, cantidades:list, precios:list, nombre:str, apellido:str, cedula:int):
        Pedido.__init__(self, id_pedido, fecha, productos, cantidades, precios)
        self.nombre = nombre
        self.apellido = apellido
        self.cedula = cedula
     def retirarPedido(self,id_pedido:int, nombre:str, apellido:str,cedula:int):
        """"
        Se retira un pedido, para ello la función va recibir el id del pedido que se quiere retirar
        y tambien es necesario el nombre, apellido y cedula de la persona que va a cancelar el pedido
        """
        if id_pedido == self.id_pedido:
            self.id_pedido = None
            self.fecha = None
            self.productos = None
            self.cantidades = None
            self.precios = None
            mensaje = "Pedido eliminado del sistema"
            print(f"Pedido retirado por el Usuario {nombre}  {apellido} con cedula ciudadana : {cedula}")
            return mensaje
        else:
           return print("Pedido no encontrado")

Uso de las clases y sus métodos 

In [7]:

productos_mercado = ['papa', 'huevos', 'pan']
cantidades_mercado = [2, 3, 4]
precios_mercado = [100, 200, 300]
#Se crea un pedido con nombre pedido1
pedido1 = Pedido(
    1,
    "2022-01-15",
    productos_mercado,
    cantidades_mercado,
    precios_mercado
)

print (pedido1.hacerPedido(productos_mercado,
    cantidades_mercado,
    precios_mercado))

usuario1 = Usuario(1,
    "2022-01-15",
    productos_mercado,
    cantidades_mercado,
    precios_mercado,
    "Carolina",
    "Molina",
    1127432)
print(usuario1.retirarPedido(1,"Carolina","Molina", 1127432))


El pedido se realizo con exito con el valor total de :2000 pesos colombianos
Pedido retirado por el Usuario Carolina  Molina con cedula ciudadana : 1127432
Pedido eliminado del sistema


Esta herramienta permitirá relacionar los pedidos realizados en un supermercado junto al usuario que realiza el mismo,
permitiendo así que pueda hacer su pedido, identificar el costo de este o retirarlo. Bajo la clase de Pedido se
podrá identificar las caracteristicas de id del pedido, fecha del pedido, productos, cantidades y precios al dia; para luego heredar estas en la clase Usuario donde se asigna los detalles de la persona que genera el pedido, tales como nombre, apellido y cédula.

Ejercicios parte 2

In [1]:
# importamos libreria de numpy
import numpy as np

Ejecricio 2.1 Resolver el siguiente sistema de ecuaciones. 

In [2]:
# Se define la matriz de coeficientes A
A = np.array([
    [2, 3, -1, 4, 5],
    [1, -2, 4, -3, 1],
    [3, 2, -3, 5, -2],
    [4, 1, -2, 3, 2],
    [1, 1, 1, 1, 1]
])

# Se define el vector B que contiene la igualdad de cada fila de la matriz de coeficiente A
B = np.array([15, 6, 11, 8, 7])
# Para resolver el sistema de ecuaciones numpy cuenta con una función que se llama linalg.solve 
# Le pasamos a la función de la matriz de coeficiente de A y el vector B
X = np.linalg.solve(A, B)


Los resultados del sistema de ecuaciones 

In [3]:
print("Los valores de x, y, z, w, v son:")
print(X)

Los valores de x, y, z, w, v son:
[-1.67741935 -7.87096774  5.12903226 10.          1.41935484]


Ejecicio 2.2 

In [8]:
# Generamos función para el calculo del factorial dado el argumento n
def factorial(n):
  """
  Función usada para el calculo del factorial dado un número n.

  In[0]: 3
  Out[0]: 6
  
  """
  if n == 0:
    return 1
  else:
    return np.prod(np.arange(1, n + 1))

# Generamos función de calculo de euler dada la ecuación.
def calculo_euler (i):
  """
  Función usada para el calculo del número de euler dado el contador de la suma

  In[0]: 9
  Out[0]: 2.71828
  
  """
  return sum(1/factorial(n) for n in range(0, i+1))
print(calculo_euler(9))

2.7182815255731922


Es necesario 9 términos para llegar a la precisión de 5 decimales en el calculo del número de euler.

Ejercicio 2.3

In [9]:
l = [2,1,1,4,3,2,1,1,2] 
# Definimos la matriz de 3X3
arr= np.array(l).reshape(3,3) 
# aplicamos laa funcion de algebra lineal de numpy  linalg con el metodo eig, 
val,vec=np.linalg.eig(arr) 


In [10]:
# en las variables val, vec almacenamos las dos tuplas que nos trae los primero para los valores y otras los vectores.
print (val,vec)

[5.44948974 0.55051026 1.        ] [[ 3.53553391e-01  3.53553391e-01  4.99600361e-16]
 [ 8.66025404e-01 -8.66025404e-01 -7.07106781e-01]
 [ 3.53553391e-01  3.53553391e-01  7.07106781e-01]]
